import { siteContent } from "@/content/site-content";

export type LegalLink = {
  href: string;
  label: string;
};

export type LegalSection = {
  id: string;
  title: string;
  paragraphs: readonly string[];
  bullets?: readonly string[];
  links?: readonly LegalLink[];
};

export type LegalDocumentContent = {
  effectiveDate: string;
  introduction: string;
  sections: readonly LegalSection[];
};

const operatorStatement = siteContent.legal.operatorStatement;
const contactEmail = siteContent.meta.contactEmail;

export const privacyPolicy: LegalDocumentContent = {
  effectiveDate: "23 July 2026",
  introduction:
    "This Privacy Policy explains how 42 handles personal information through this website and its HubSpot enquiry form. It reflects the technology and form behaviour inspected on 23 July 2026.",
  sections: [
    {
      id: "operator",
      title: "Who operates this website",
      paragraphs: [
        operatorStatement,
        `Privacy questions and requests may be sent to ${contactEmail}. No public street address is provided on this website.`,
      ],
    },
    {
      id: "information-provided",
      title: "Information you choose to provide",
      paragraphs: [
        "The HubSpot form asks for first name, last name, work email address, company name, employment role, website URL, HubSpot status, primary challenge, and project timing. Work email and company name are required by the current form; the other visible fields are optional.",
        `If you contact 42 by email instead, 42 receives the information included in your email and the address from which it was sent.`,
      ],
    },
    {
      id: "technical-information",
      title: "Technical information",
      paragraphs: [
        "The HubSpot form includes technical submission context generated by the embed. The inspected context included the referring page, browser user-agent string, URL parameters, page URL and title, locale, form and portal identifiers, rendered-field identifiers, CAPTCHA status, and form-performance metadata.",
        "The hosting platform and web server necessarily receive standard request information to deliver and protect the site. This can include the requested URL, IP address, browser or user-agent information, request time, and response status.",
      ],
    },
    {
      id: "purposes",
      title: "Why the information is used",
      paragraphs: [
        "Information submitted through the form or by email is intended to be used to understand the enquiry, respond to the person who contacted 42, assess whether there is a sensible next step, arrange follow-up where requested, maintain necessary business records, and troubleshoot or secure the website and form.",
        "The website does not currently use the enquiry form for a newsletter, advertising audiences, behavioural profiling, or automated marketing journeys.",
      ],
    },
    {
      id: "legal-basis",
      title: "Legal basis",
      paragraphs: [
        "The appropriate legal basis depends on the visitor’s location and the context of the enquiry. The intended processing is limited to responding to steps requested before a possible engagement, operating the website, and pursuing proportionate business and security interests.",
      ],
    },
    {
      id: "hubspot",
      title: "HubSpot form processing",
      paragraphs: [
        "The Contact page loads a HubSpot-hosted script and form frame. A completed form is submitted to HubSpot’s forms service and becomes available to 42 in its HubSpot account. HubSpot processes customer-submitted data on behalf of its customers under its applicable service terms and data-processing arrangements.",
        "The approved embed is the only HubSpot website functionality currently active. The site does not load the separate HubSpot website tracking code.",
      ],
      links: [
        {
          href: "https://legal.hubspot.com/privacy-policy",
          label: "Read HubSpot’s Privacy Policy",
        },
      ],
    },
    {
      id: "providers",
      title: "Service providers and third-party requests",
      paragraphs: [
        "This website is delivered through Render and uses HubSpot for the enquiry form. The form embed makes requests to HubSpot-controlled form, static-asset, submission, and form-branding services.",
        "The inspected live form also made requests to HubSpot-controlled API and diagnostic services.",
        "The site’s primary and secondary fonts are served locally by the Next.js application. No Google Analytics, Google Tag Manager, Microsoft Clarity, HubSpot website tracking code, LinkedIn Insight Tag, Meta Pixel, newsletter tracking, or advertising pixel is active.",
      ],
    },
    {
      id: "cookies-storage",
      title: "Cookies and browser storage",
      paragraphs: [
        "The inspected live form session identified cookies named __cf_bm on HubSpot-controlled domains. The observed cookies were Secure, SameSite=None, and HttpOnly, so they were not accessible to the website or form through JavaScript.",
        "The inspection did not identify any script-accessible cookies or entries in localStorage or sessionStorage before or after a synthetic HubSpot form submission. No cookie banner is active on the current site.",
        "HubSpot controls the form frame and may change its technical implementation. Storage behaviour can also vary with browser settings, location, account configuration, and future HubSpot changes.",
      ],
    },
    {
      id: "sharing",
      title: "When information is shared",
      paragraphs: [
        "Enquiry information is made available to 42 and processed through HubSpot. Technical request information is handled by the relevant hosting and infrastructure providers as needed to deliver and secure the site.",
        "42 does not intend to sell enquiry information or share it for cross-context behavioural advertising. Information may need to be disclosed where required by applicable law or a valid legal process.",
      ],
    },
    {
      id: "international",
      title: "International processing",
      paragraphs: [
        "42 serves organisations across North America and EMEA. HubSpot and Render may process information in countries other than the country in which a visitor is located.",
      ],
    },
    {
      id: "retention",
      title: "How long information is kept",
      paragraphs: [
        "42 keeps personal information only for as long as it is reasonably needed to respond to the enquiry, manage any resulting relationship, maintain necessary business records, meet legal obligations, resolve disputes, or protect the website and business.",
      ],
    },
    {
      id: "rights",
      title: "Privacy rights and requests",
      paragraphs: [
        `Privacy rights depend on the law that applies to the individual and the processing. A person may contact ${contactEmail} to ask about personal information held by 42 or to make a request. 42 may need reasonable information to verify the requester and locate the relevant record.`,
      ],
    },
    {
      id: "security-updates",
      title: "Security, changes, and contact",
      paragraphs: [
        "42 uses proportionate technical and organisational measures intended to protect information, but no internet transmission or storage system can be guaranteed completely secure.",
        `This policy may be updated when the website, form, providers, or legal requirements change. Questions may be sent to ${contactEmail}.`,
      ],
    },
  ],
};

export const termsOfUse: LegalDocumentContent = {
  effectiveDate: "23 July 2026",
  introduction:
    "These Terms of Use apply to access to and use of the public 42 website. They do not govern paid consultancy work, which must be covered by a separate written engagement agreement.",
  sections: [
    {
      id: "operator",
      title: "Website operator",
      paragraphs: [
        operatorStatement,
        `Questions about these terms may be sent to ${contactEmail}.`,
      ],
    },
    {
      id: "acceptance",
      title: "Acceptance and scope",
      paragraphs: [
        "By accessing or using this website, a visitor agrees to use it in accordance with these Terms of Use and applicable law. A visitor who does not agree should stop using the site.",
        "These terms apply only to the public website and its content. They do not create a consultancy engagement, a client relationship, or an obligation for 42 to accept or respond to an enquiry.",
      ],
    },
    {
      id: "permitted-use",
      title: "Permitted use",
      paragraphs: [
        "The website may be used to learn about 42, read published Insights, evaluate services, and contact 42 for legitimate business purposes.",
      ],
      bullets: [
        "Do not interfere with the operation or security of the website.",
        "Do not attempt unauthorised access to the website, its hosting, forms, or connected systems.",
        "Do not use automated requests in a way that degrades the service or ignores reasonable technical restrictions.",
        "Do not submit unlawful, misleading, abusive, infringing, or malicious material through the form or by email.",
        "Do not misrepresent an affiliation with 42 or use the site to impersonate another person or organisation.",
      ],
    },
    {
      id: "content",
      title: "Website content and information",
      paragraphs: [
        "The website provides general information about HubSpot consulting, CRM, automation, integrations, websites, accessibility, and related operational topics. It is not legal, tax, financial, security, or other regulated professional advice.",
        "42 aims to keep the content clear and useful, but does not promise that every item is complete, current, error-free, or suitable for a visitor’s specific circumstances. Visitors should evaluate important decisions in their own context.",
      ],
    },
    {
      id: "outcomes",
      title: "No guaranteed outcomes",
      paragraphs: [
        "Website content and conversations initiated through the site do not guarantee search rankings, revenue, conversion performance, HubSpot results, integration outcomes, project acceptance, delivery timing, or any other business result.",
      ],
    },
    {
      id: "intellectual-property",
      title: "Intellectual property",
      paragraphs: [
        "Unless stated otherwise, the website design, original copy, diagrams, and other original materials are intended to be owned by or licensed to Madeyoulookagency LLC. Visitors may view and make reasonable internal reference to public pages, but may not reproduce, republish, sell, or present substantial parts of the site as their own without written permission or another lawful basis.",
      ],
    },
    {
      id: "third-parties",
      title: "Third-party services, links, and marks",
      paragraphs: [
        "The website uses a HubSpot form and may link to third-party websites. Third-party services and websites are governed by their own terms and privacy practices, and 42 does not control their availability or content.",
        "HubSpot and related product names and marks belong to their respective owners. References to HubSpot describe the subject of 42’s services and do not, by themselves, state or imply a partner tier, certification, endorsement, or other status.",
      ],
    },
    {
      id: "engagements",
      title: "Consultancy engagements",
      paragraphs: [
        "Any consultancy, implementation, development, support, or other paid service must be agreed separately in writing. The relevant proposal, statement of work, order form, or services agreement will govern scope, fees, delivery responsibilities, intellectual property, confidentiality, data handling, warranties, and liability for that engagement.",
      ],
    },
    {
      id: "availability",
      title: "Website availability",
      paragraphs: [
        "42 may change, suspend, or withdraw website content or functionality where reasonably necessary. The site may sometimes be unavailable because of maintenance, provider outages, security work, or events outside 42’s reasonable control.",
      ],
    },
    {
      id: "liability",
      title: "Liability for website use",
      paragraphs: [
        "Nothing in these terms is intended to exclude or limit liability that cannot lawfully be excluded or limited. Subject to that qualification, the website is provided for general informational use and visitors remain responsible for decisions made using its content.",
      ],
    },
    {
      id: "governing-law",
      title: "Governing law",
      paragraphs: [
        `These Terms of Use are governed by ${siteContent.legal.governingLaw}.`,
      ],
    },
    {
      id: "changes-contact",
      title: "Changes and contact",
      paragraphs: [
        `42 may update these terms to reflect changes to the website, business, providers, or legal requirements. The date shown at the top identifies the current version. Questions may be sent to ${contactEmail}.`,
      ],
    },
  ],
};
